Repository Nirclaw/zoologico_campus, pull requests merged in 2023-08, with the labels that each got.

#2 [GEN-22] Testeo data
  db/database.mongodb
  db/insersionData.mongodb
Labels: enhancement

#3 Database - correccion
  db/database.mongodb
  db/insersionData.mongodb
Labels: bug

#4 GEN-24 Consultas
  db/consultas.mongodb
  db/database.mongodb
  db/insersionData.mongodb
Labels: enhancement

#7 Conexion a la base de datos de mongo
  conexion/conexion.js
  package.json
Labels: enhancement

#8 GEN-32 feat: :construction: Se crean los archivos Routers
  routers/animales.js
  routers/cliente.js
  routers/contador.js
  routers/empleados.js
  routers/insumos.js
  routers/taquilla.js
  routers/zonas.js
Labels: enhancement

#9 GEN-33 refactor: :recycle: Servidor
  app.js
  routers/cliente.js
  routers/contador.js
Labels: enhancement

#10 GEN-49 docs: :memo: README
  README.md
Labels: documentation

#11 GEN-40 Login
  app.js
  config/variables.js
  db/database.mongodb
  db/insersionData.mongodb
  jwt/jwt.js
  jwt/passport.js
  login/login.js
  middleware/limit.js
  package.json
  routers/animales.js
  routers/empleados.js
  routers/insumos.js
  routers/taquilla.js
  routers/zonas.js
Labels: enhancement

#13 [ GEN-42 ]End point animales
  db/database.mongodb
  helpers/autoincrement.js
  routers/animales.js
  versiones/V1/animales.js
  versiones/V2/animales.js
Labels: enhancement

#14 GEN-46 feat: :sparkles: Se agrega los enpoinds de taquilla y sus versiones
  routers/taquilla.js
  versiones/V1/taquilla.js
  versiones/V2/taquilla.js
Labels: enhancement

#15 [ GEN-44 ] End point insumos
  routers/insumos.js
  versiones/V1/insumos.js
  versiones/V2/insumos.js
Labels: enhancement

#17 Refactor code en la coleccion de Insumos, Zonas, Animales
  versiones/V2/animales.js
  versiones/V2/insumos.js
  versiones/V2/zonas.js
Labels: enhancement

#21 [ GEN-50 ] Dto animales
  middleware/DTO/animales.js
  routers/animales.js
  versiones/V2/animales.js
Labels: enhancement

#22 [ GEN-54 ] Dto insumos
  middleware/DTO/insumos.js
  routers/insumos.js
  versiones/V2/insumos.js
Labels: enhancement

#23 [ GEN-56 ] Dto zonas
  middleware/DTO/zonas.js
  routers/zonas.js
  versiones/V2/zonas.js
Labels: enhancement
